### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [prince-an/Leon_zshTheme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Z1an-Wang** [comment]
Hi,


It's great honor for me to be selected, and I'm really keen to share my code. After some search on the given website (It's really useful :D ) , I have already update the license state as MIT license which is very convenient for others to use it.


Best,
Leon


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "prince-an/Leon_zshTheme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 凌晨1:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[prince-an/Leon_zshTheme] Please add a license file (#1)





 
I'd like to add this to awesome-zsh-plugins, but it doesn't have a license file.
 
Please add a license file - if you don't have one in mind,  I recommend using choosealicense.com to help choose an appropriate one.
 
Thanks!
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
